let dramas = [
  {
    id: 1,
    title: "Hidden Love",
    category: "C-Drama",
    rating: "9.7",
    image: "https://i.pinimg.com/564x/c6/16/1f/c6161f5e4b8a5e8b9c3d4e5f6a7b8c9d.jpg",
    description: "A romantic story about childhood love",
    year: "2023",
    episodes: 24,
    genre: "Romance, Drama",
    status: "Completed",
    about: "Ye ek beautiful love story hai jo school life se start hoti hai.",
    favorites: false,
    watchHistory: true
  },
  {
    id: 2,
    title: "Business Proposal",
    category: "K-Drama",
    rating: "9.5",
    image: "https://i.pinimg.com/564x/a1/b2/c3/a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6.jpg",
    description: "A hilarious fake romance story",
    year: "2022",
    episodes: 12,
    genre: "Romance, Comedy",
    status: "Completed",
    about: "Shin Ha-ri pretends to be her friend to date Lee Kong-shin, but things get complicated.",
    favorites: true,
    watchHistory: true
  },
  {
    id: 3,
    title: "The Glory",
    category: "K-Drama",
    rating: "9.6",
    image: "https://i.pinimg.com/564x/d4/e5/f6/d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9.jpg",
    description: "Dark revenge drama",
    year: "2023",
    episodes: 16,
    genre: "Drama, Thriller",
    status: "Completed",
    about: "Moon Dong-eun plans revenge on her middle school bullies.",
    favorites: true,
    watchHistory: false
  },
  {
    id: 4,
    title: "Squid Game",
    category: "K-Drama",
    rating: "9.4",
    image: "https://i.pinimg.com/564x/b7/c8/d9/b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2.jpg",
    description: "Survival game show drama",
    year: "2021",
    episodes: 9,
    genre: "Thriller, Drama",
    status: "Returning",
    about: "456 players compete in deadly games for 45.6 billion won.",
    favorites: false,
    watchHistory: true
  },
  {
    id: 5,
    title: "Your Name",
    category: "Movie",
    rating: "9.8",
    image: "https://i.pinimg.com/564x/e0/f1/a2/e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5.jpg",
    description: "Beautiful anime romance movie",
    year: "2016",
    episodes: 1,
    genre: "Romance, Fantasy",
    status: "Completed",
    about: "Two teenagers share a profound connection after they swap bodies.",
    favorites: true,
    watchHistory: true
  },
  {
    id: 6,
    title: "Demon Slayer",
    category: "Anime",
    rating: "9.6",
    image: "https://i.pinimg.com/564x/f2/a3/b4/f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7.jpg",
    description: "Epic anime action series",
    year: "2019",
    episodes: 55,
    genre: "Action, Fantasy",
    status: "Returning",
    about: "Tanjiro becomes a demon slayer to save his sister.",
    favorites: true,
    watchHistory: true
  }
];